config/routes.rb
MobileReserva::Application.routes.draw do
  

  resources :seats

  root :to => 'flights#index'
  
  
  resources :flights

end

app/models/flight.rb
class Flight < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
#  	before_filter :parse_facebook_cookies
#	def parse_facebook_cookies
# 		@facebook_cookies = Koala::Facebook::OAuth.new.get_user_info_from_cookie(cookies)
#	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flights }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find(params[:id])
    @seats = Seat.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flight }
      format.json { render json: @seats }
    end
  end

  # GET /flights/new
  # GET /flights/new.json
  def new
    @flight = Flight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find(params[:id])
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(params[:flight])

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render json: @flight, status: :created, location: @flight }
      else
        format.html { render action: "new" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flights/1
  # PUT /flights/1.json
  def update
    @flight = Flight.find(params[:id])

    respond_to do |format|
      if @flight.update_attributes(params[:flight])
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :ok }
    end
  end
end

app/controllers/oauth_controller.rb
class OauthController < ActionController
def start
redirect_to client.web_server.authorize_url(
:redirect_uri =&gt; oauth_callback_url, :scope =&gt; 'email'
)
end

def callback
access_token = client.web_server.get_access_token(
params[:code], :redirect_uri =&gt; oauth_callback_url
)

session[:fb_user] = JSON.parse access_token.get('/me')
# in reality you would at this point store the access_token.token value as well as
# any user info you wanted

redirect_to :controller =&gt; :users, :action =&gt; :login_process_facebook, :token =&gt; access_token.token

end

protected

def client
facebook_settings = YAML::load(File.open("#{RAILS_ROOT}/config/oauth.yml"))
@client ||= OAuth2::Client.new(
"#{facebook_settings[RAILS_ENV]['application_id']}", "#{facebook_settings[RAILS_ENV]['secret_key']}",
:site =&gt; 'https://graph.facebook.com'
)
end
end

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seats }
    end
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.json
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(params[:seat])

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render json: @seat, status: :created, location: @seat }
      else
        format.html { render action: "new" }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.json
  def update
    @seat = Seat.find(params[:id])

    respond_to do |format|
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to seats_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :código %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :aerolínea %><br />
    <%= f.text_field :aerolinea %>
  </div>
  <div class="field">
    <%= f.label :salida %><br />
    <%= f.datetime_select :salida %>
  </div>
  <div class="field">
    <%= f.label :llegada %><br />
    <%= f.datetime_select :llegada %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br />
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editando Vuelo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @flight %> |
<%= link_to 'Atrás', flights_path %>

app/views/flights/index.html.erb
    <p><strong class="ui-link">Bienvenido.</strong> Busque y realice la reserva de su vuelo.</p>

    <ul data-role="listview" data-inset="true" data-filter="true">
       
        <% @flights.each do |flight| %>
            <li>
                <%= link_to flight.codigo , flight %>
            </li>
            
        <% end %>
    </ul>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @flight.codigo %>
</h1>

<p>
  <b>Aerolínea:</b>
  <%= @flight.aerolinea %>
</p>
<p>
  <b>Ciudad:</b>
  <%= @flight.ciudad %>
</p>
<table>
<tr>
  <td><b>Salida:</b>
  </td>
  <td><b>Llegada:</b>
  </td>
</tr>
<tr>
  <td><p>
  <%= @flight.salida %>
</p>
  </td>
  <td><p>
  
  <%= @flight.llegada %>
</p>
  </td>
</tr>
</table>


Seleccionar Asiento:
<select class="large" name="mediumSelect" id="mediumSelect"> 
  <% @seats.each do |seat| %>
    <% if seat.vuelo==@flight.codigo && seat.estado==false %>
      <option value="<%= seat.id %>">Asiento N° <%= seat.numero %> (<%= seat.posicion %>)</option>
    <% end %>
  <% end %>
</select>

 <button id="btnReservar" data-icon="star" data-theme="b" data-form="ui-btn-up-a" class="ui-btn-hidden" aria-disabled="false">Realizar Reserva</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reserva de Vuelos</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet"  href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />   
	<link rel="stylesheet" href="http://jquerymobile.com/demos/1.0/docs/_assets/css/jqm-docs.css" />
	<script src="http://code.jquery.com/jquery-1.6.4.js"></script>
	<script src="http://jquerymobile.com/demos/1.0/experiments/themeswitcher/jquery.mobile.themeswitcher.js"></script>
	<script src="http://jquerymobile.com/demos/1.0/docs/_assets/js/jqm-docs.js"></script>
	<script src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	<script language=javascript>
       $(document).bind("mobileinit", function () {
             $.extend(  $.mobile , { 
               ajaxEnabled : false  });
       });


  </script>
</head>
<body>
	<div data-role="page" id="one">
		<%= link_to image_tag("fb_button.gif"), :controller => 'oauth', :action => 'start' %>

		<fb:login-button onlogin='window.location="/oauth/callback"' perms="email" ></fb:login-button>

<div style="float:right">
  <div style="float:left;padding-right:10px">
    <fb:login-button onlogin='window.location="/oauth/start"' perms="email" >
    </fb:login-button>
  </div>
  <div style="float:left">
  </div>
</div>

		<div data-role="header" data-theme="b">
		
			<h1>Reserva de Vuelos</h1>
			<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Home</a>
			<a  data-rel="back" data-icon="back" data-iconpos="notext" data-add-back-btn="true" class="ui-btn-right" data-back-btn-text="previous">Atrás</a>

		</div><!-- /header -->

		
		<div data-role="content"  class="ui-body ui-body-b">
			<%= yield %>
		</div>
		
		
		<div data-role="footer" class="footer-docs" data-theme="b">
				<p>&copy; DSD 2012-0 M1 QWERTY</p>
		</div>	
		
	</div>
</body>
</html>

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br />
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :posicion %><br />
    <%= f.text_field :posicion %>
  </div>
  <div class="field">
    <%= f.label :vuelo %><br />
    <%= f.text_field :vuelo %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Numero</th>
    <th>Posicion</th>
    <th>Vuelo</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seats.each do |seat| %>
  <tr>
    <td><%= seat.numero %></td>
    <td><%= seat.posicion %></td>
    <td><%= seat.vuelo %></td>
    <td><%= seat.estado %></td>
    <td><%= link_to 'Show', seat %></td>
    <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
    <td><%= link_to 'Destroy', seat, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numero:</b>
  <%= @seat.numero %>
</p>

<p>
  <b>Posicion:</b>
  <%= @seat.posicion %>
</p>

<p>
  <b>Vuelo:</b>
  <%= @seat.vuelo %>
</p>

<p>
  <b>Estado:</b>
  <%= @seat.estado %>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>